# Generated by Django 3.2.9 on 2022-03-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Session_years',
        ),
    ]
