# Generated by Django 3.2.9 on 2022-03-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220301_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_year',
            name='session_end',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_data',
            field=models.CharField(max_length=100),
        ),
    ]
